### ISSUE TITLE
Should I fork, is this still being worked on?

### ISSUE THREAD

**Issue by Jenpatrick** [brianlevis/nerf-iron-dome#6]
Is this still being worked on, before I try to work from is again, 

One day, I might just go with the idea of a tensorflow based system, which the RPI4 8gb will still likely choke on horribly, just as it just with OPencv/CV2?  

( (Note for other who read this pr: Don't ask when) it's fall in Boston, maybe I'll write it when it's super late in the winter..) )

(If  I do a new thing, it would be announced on reddits nerfmods group, or on fbook https://www.facebook.com/groups/164130663628549 )

**Comment by brianlevis** [comment]
To be honest, I don't see myself picking this up soon - it's probably best to fork or create a new project!

If I was to work on this again, I'd probably rewrite most of this stuff - the code quality and project organization are pretty bad :D

**Comment by Jenpatrick** [comment]
Cool, them pls close. :)
